
import type { Icon as LucideIconType } from "lucide-react";
import { 
  Sparkles, Anchor, Swords, Zap, Ghost, Ban, MountainSnow, Flame, Snowflake, 
  Puzzle, ShieldOff, Waves, ShieldAlert, Trees, Bone, CloudLightning, 
  Target, Moon, Copy as CopyIconLucide, Axe as AxeIconLucide,
  Shield, FlaskConical, Brain, Bird, Droplets, Coins, Beer, Bug, Footprints, Dice5, // Replaced Spider with Bug
  Handshake, Cog, Shell, Sunrise, Hammer, ShieldPlus, Circle, BookOpen as BookIcon,
  Plane, Nut, Sun, Ship, HeartHandshake, Dog, Hand, Eye, PawPrint, VolumeX, Fish, 
  Waypoints as GateIcon, UserCircle2, Pickaxe, VenetianMask, SprayCan, Gem, Palmtree, // Removed Swirl
  Siren, Rat, Castle, Wheat, Dices, Unplug, Box, ShieldCheck, GitFork, Bot, Rabbit, Crown, Drama,
  Skull, Crosshair, EyeOff, Tornado, Activity, Bomb, Wind, Home // Added Wind, Bomb, Home. Removed Tower.
} from "lucide-react";

export const defaultHeroNames = [
  'Abaddon', 'Alchemist', 'Ancient Apparition', 'Anti-Mage', 'Arc Warden', 'Axe', 'Bane', 'Batrider', 'Beastmaster', 
  'Bloodseeker', 'Bounty Hunter', 'Brewmaster', 'Bristleback', 'Broodmother', 'Centaur Warrunner', 'Chaos Knight', 
  'Chen', 'Clinkz', 'Clockwerk', 'Crystal Maiden', 'Dark Seer', 'Dark Willow', 'Dawnbreaker', 'Dazzle', 
  'Death Prophet', 'Disruptor', 'Doom', 'Dragon Knight', 'Drow Ranger', 'Earth Spirit', 'Earthshaker', 
  'Elder Titan', 'Ember Spirit', 'Enchantress', 'Enigma', 'Faceless Void', 'Grimstroke', 'Gyrocopter', 
  'Hoodwink', 'Huskar', 'Invoker', 'Io', 'Jakiro', 'Juggernaut', 'Keeper of the Light', 'Kez', 'Kunkka', 
  'Legion Commander', 'Leshrac', 'Lich', 'Lifestealer', 'Lina', 'Lion', 'Lone Druid', 'Luna', 'Lycan', 
  'Magnus', 'Marci', 'Mars', 'Medusa', 'Meepo', 'Mirana', 'Monkey King', 'Morphling', 'Muerta', 
  'Naga Siren', "Nature's Prophet", 'Necrophos', 'Night Stalker', 'Nyx Assassin', 'Ogre Magi', 'Omniknight', 
  'Oracle', 'Outworld Destroyer', // Changed from Devourer to match provided color list
  'Pangolier', 'Phantom Assassin', 'Phantom Lancer', 'Phoenix', 'Primal Beast', 
  'Puck', 'Pudge', 'Pugna', 'Queen of Pain', 'Razor', 'Riki', 'Ringmaster', 'Rubick', 'Sand King', 
  'Shadow Demon', 'Shadow Fiend', 'Shadow Shaman', 'Silencer', 'Skywrath Mage', 'Slardar', 'Slark', 
  'Snapfire', 'Sniper', 'Spectre', 'Spirit Breaker', 'Storm Spirit', 'Sven', 'Techies', 'Templar Assassin', 
  'Terrorblade', 'Tidehunter', 'Timbersaw', 'Tinker', 'Tiny', 'Treant Protector', 'Troll Warlord', 'Tusk', 
  'Underlord', 'Undying', 'Ursa', 'Vengeful Spirit', 'Venomancer', 'Viper', 'Visage', 'Void Spirit', 
  'Warlock', 'Weaver', 'Windranger', 'Winter Wyvern', 'Witch Doctor', 'Wraith King', 'Zeus'
];

export const heroIconMap: Record<string, LucideIconType> = {
  'Abaddon': ShieldCheck,
  'Alchemist': FlaskConical,
  'Ancient Apparition': Snowflake,
  'Anti-Mage': Ban,
  'Arc Warden': GitFork,
  'Axe': AxeIconLucide,
  'Bane': Brain,
  'Batrider': Flame,
  'Beastmaster': AxeIconLucide,
  'Bloodseeker': Droplets,
  'Bounty Hunter': Coins,
  'Brewmaster': Beer,
  'Bristleback': Pickaxe,
  'Broodmother': Bug,
  'Centaur Warrunner': Footprints,
  'Chaos Knight': Dices,
  'Chen': Handshake,
  'Clinkz': Flame,
  'Clockwerk': Cog,
  'Crystal Maiden': Snowflake,
  'Dark Seer': Shell,
  'Dark Willow': Palmtree,
  'Dawnbreaker': Sunrise,
  'Dazzle': ShieldPlus,
  'Death Prophet': Ghost,
  'Disruptor': CloudLightning,
  'Doom': Flame,
  'Dragon Knight': Castle,
  'Drow Ranger': Target,
  'Earth Spirit': MountainSnow,
  'Earthshaker': MountainSnow,
  'Elder Titan': Hammer,
  'Ember Spirit': Flame,
  'Enchantress': Rabbit,
  'Enigma': Gem,
  'Faceless Void': Circle,
  'Grimstroke': SprayCan,
  'Gyrocopter': Plane,
  'Hoodwink': Nut,
  'Huskar': Flame,
  'Invoker': Sparkles,
  'Io': Circle,
  'Jakiro': Flame,
  'Juggernaut': Swords,
  'Keeper of the Light': Sun,
  'Kez': Puzzle, // Placeholder, no specific hero named Kez
  'Kunkka': Ship,
  'Legion Commander': Swords,
  'Leshrac': Zap,
  'Lich': Snowflake,
  'Lifestealer': Rat,
  'Lina': Flame,
  'Lion': Zap,
  'Lone Druid': PawPrint,
  'Luna': Moon,
  'Lycan': Dog,
  'Magnus': Tornado,
  'Marci': Hand,
  'Mars': Shield,
  'Medusa': Siren,
  'Meepo': CopyIconLucide,
  'Mirana': Moon,
  'Monkey King': Pickaxe,
  'Morphling': Waves,
  'Muerta': Crosshair,
  'Naga Siren': Siren,
  "Nature's Prophet": Trees,
  'Necrophos': Skull,
  'Night Stalker': Moon,
  'Nyx Assassin': Bug,
  'Ogre Magi': Dice5,
  'Omniknight': ShieldPlus,
  'Oracle': Eye,
  'Outworld Destroyer': Brain, // Using Brain for OD
  'Pangolier': Swords,
  'Phantom Assassin': VenetianMask,
  'Phantom Lancer': CopyIconLucide,
  'Phoenix': Flame,
  'Primal Beast': PawPrint,
  'Puck': Sparkles,
  'Pudge': Anchor,
  'Pugna': Home,
  'Queen of Pain': Drama,
  'Razor': Zap,
  'Riki': EyeOff,
  'Ringmaster': Puzzle, // Placeholder
  'Rubick': CopyIconLucide,
  'Sand King': Bug,
  'Shadow Demon': Ghost,
  'Shadow Fiend': Ghost,
  'Shadow Shaman': Bot,
  'Silencer': VolumeX,
  'Skywrath Mage': Bird,
  'Slardar': Fish,
  'Slark': Waves,
  'Snapfire': Flame,
  'Sniper': Target,
  'Spectre': Ghost,
  'Spirit Breaker': Activity,
  'Storm Spirit': CloudLightning,
  'Sven': ShieldAlert,
  'Techies': Bomb,
  'Templar Assassin': ShieldOff,
  'Terrorblade': Swords,
  'Tidehunter': Anchor,
  'Timbersaw': AxeIconLucide,
  'Tinker': Cog,
  'Tiny': Trees,
  'Treant Protector': Trees,
  'Troll Warlord': AxeIconLucide,
  'Tusk': Snowflake,
  'Underlord': GateIcon,
  'Undying': Skull,
  'Ursa': PawPrint,
  'Vengeful Spirit': Sparkles,
  'Venomancer': Droplets,
  'Viper': Droplets,
  'Visage': Bird,
  'Void Spirit': Sparkles,
  'Warlock': BookIcon,
  'Weaver': Bug,
  'Windranger': Wind,
  'Winter Wyvern': Snowflake,
  'Witch Doctor': Bone,
  'Wraith King': Crown,
  'Zeus': CloudLightning,
  'Default': Puzzle,
};

export const heroColorMap: Record<string, string> = {
  "Abaddon": "#4a4a4a",
  "Alchemist": "#8b4513",
  "Axe": "#dc143c",
  "Beastmaster": "#cd853f",
  "Brewmaster": "#ff6347",
  "Bristleback": "#8b4513",
  "Centaur Warrunner": "#a0522d",
  "Chaos Knight": "#800080",
  "Clockwerk": "#ff4500",
  "Dawnbreaker": "#ffd700",
  "Doom": "#ff0000",
  "Dragon Knight": "#ff6347",
  "Earth Spirit": "#8b4513",
  "Earthshaker": "#a0522d",
  "Elder Titan": "#4682b4",
  "Huskar": "#ff4500",
  "Io": "#00ffff",
  "Kunkka": "#4682b4",
  "Legion Commander": "#dc143c",
  "Lifestealer": "#8b0000",
  "Magnus": "#4682b4",
  "Marci": "#ff69b4",
  "Mars": "#dc143c",
  "Night Stalker": "#2f4f4f",
  "Omniknight": "#ffd700",
  "Primal Beast": "#8b4513",
  "Pudge": "#228b22",
  "Sand King": "#daa520",
  "Slardar": "#4682b4",
  "Snapfire": "#ff4500",
  "Spirit Breaker": "#9370db",
  "Sven": "#1e90ff",
  "Tidehunter": "#006400",
  "Timbersaw": "#32cd32",
  "Tiny": "#696969",
  "Tusk": "#87ceeb",
  "Underlord": "#8b0000",
  "Undying": "#228b22",
  "Wraith King": "#32cd32",
  "Anti-Mage": "#9370db",
  "Arc Warden": "#1e90ff",
  "Bloodseeker": "#dc143c",
  "Bounty Hunter": "#daa520",
  "Broodmother": "#8b0000",
  "Clinkz": "#2f4f4f",
  "Drow Ranger": "#87ceeb",
  "Ember Spirit": "#ff4500",
  "Faceless Void": "#9370db",
  "Gyrocopter": "#ff6347",
  "Hoodwink": "#8b4513",
  "Juggernaut": "#ff6347",
  "Luna": "#1e90ff",
  "Medusa": "#32cd32",
  "Meepo": "#8b4513",
  "Mirana": "#87ceeb",
  "Monkey King": "#daa520",
  "Morphling": "#1e90ff",
  "Naga Siren": "#20b2aa",
  "Nyx Assassin": "#9370db",
  "Pangolier": "#daa520",
  "Phantom Assassin": "#4b0082",
  "Phantom Lancer": "#1e90ff",
  "Razor": "#1e90ff",
  "Riki": "#9370db",
  "Shadow Fiend": "#8b0000",
  "Slark": "#2f4f4f",
  "Sniper": "#daa520",
  "Spectre": "#9370db",
  "Templar Assassin": "#ff69b4",
  "Terrorblade": "#8b0000",
  "Troll Warlord": "#8b4513",
  "Ursa": "#8b4513",
  "Vengeful Spirit": "#9370db",
  "Venomancer": "#32cd32",
  "Viper": "#32cd32",
  "Weaver": "#daa520",
  "Ancient Apparition": "#87ceeb",
  "Bane": "#4b0082",
  "Batrider": "#ff4500",
  "Chen": "#ffd700",
  "Crystal Maiden": "#87ceeb",
  "Dark Seer": "#9370db",
  "Dark Willow": "#9370db",
  "Dazzle": "#ff69b4",
  "Death Prophet": "#32cd32",
  "Disruptor": "#1e90ff",
  "Enchantress": "#32cd32",
  "Enigma": "#4b0082",
  "Grimstroke": "#2f4f4f",
  "Invoker": "#daa520",
  "Jakiro": "#ff4500",
  "Keeper of the Light": "#ffd700",
  "Leshrac": "#1e90ff",
  "Lich": "#87ceeb",
  "Lina": "#ff0000",
  "Lion": "#4b0082",
  "Muerta": "#32cd32",
  "Nature's Prophet": "#32cd32",
  "Necrophos": "#32cd32",
  "Ogre Magi": "#1e90ff",
  "Oracle": "#ffd700",
  "Outworld Destroyer": "#1e90ff",
  "Puck": "#ff69b4",
  "Queen of Pain": "#ff69b4",
  "Rubick": "#32cd32",
  "Shadow Demon": "#9370db",
  "Shadow Shaman": "#9370db",
  "Silencer": "#9370db",
  "Skywrath Mage": "#1e90ff",
  "Storm Spirit": "#1e90ff",
  "Techies": "#daa520",
  "Tinker": "#ff6347",
  "Visage": "#2f4f4f",
  "Void Spirit": "#9370db",
  "Warlock": "#ff0000",
  "Windranger": "#32cd32",
  "Winter Wyvern": "#87ceeb",
  "Witch Doctor": "#9370db",
  "Zeus": "#1e90ff",
};

// Fallback color if hero not in map
export const FALLBACK_HERO_COLOR = '#FF3BEA'; // Neon Pink (Primary Theme Color)
