
"use client";

import * as React from "react";
import Link from "next/link";
import { doc, getDoc, collection, query, where, getDocs, orderBy } from "firebase/firestore";
import { db } from "@/lib/firebase";
import type { Team, Match } from "@/lib/definitions";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Crown, Loader2, ShieldQuestion, UserPlus, Fingerprint, Copy } from "lucide-react";
import { RosterCard } from "@/components/app/my-team/RosterCard";
import { SchedulingCard } from "@/components/app/my-team/SchedulingCard";
import { TeamStatsGrid } from "@/components/app/my-team/TeamStatsGrid";
import { PlayerAnalyticsTable } from "@/components/app/my-team/PlayerAnalyticsTable";
import { MatchHistoryTable } from "@/components/app/my-team/MatchHistoryTable";
import { NextMatchCard } from "@/components/app/my-team/NextMatchCard";
import { MyTeamHeader } from "@/components/app/my-team/MyTeamHeader";
import { TeamStatusCard } from "@/components/app/my-team/TeamStatusCard";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/context/AuthContext";
import { useToast } from "@/hooks/use-toast";
import { getUserTeam } from "@/lib/team";

async function getMyTeamData(teamId: string): Promise<{ team: Team | undefined, upcomingMatches: Match[], pastMatches: Match[] }> {
  try {
    const teamDocRef = doc(db, "teams", teamId);
    const teamDocSnap = await getDoc(teamDocRef);

    if (!teamDocSnap.exists()) {
      return { team: undefined, upcomingMatches: [], pastMatches: [] };
    }

    const team = { id: teamDocSnap.id, ...teamDocSnap.data() } as Team;

    const matchesRef = collection(db, "matches");
    const q = query(matchesRef, where("teams", "array-contains", teamId));
    const querySnapshot = await getDocs(q);
    const teamMatches = querySnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as Match));

    const upcomingMatches = teamMatches
      .filter((m) => m.status === 'upcoming')
      .sort((a, b) => new Date(a.dateTime).getTime() - new Date(b.dateTime).getTime());

    const pastMatches = teamMatches
      .filter((m) => m.status === 'completed')
      .sort((a, b) => new Date(b.dateTime).getTime() - new Date(a.dateTime).getTime());

    return { team, upcomingMatches, pastMatches };
  } catch (error) {
    console.error("Error fetching team data:", error);
    return { team: undefined, upcomingMatches: [], pastMatches: [] };
  }
}

// The main dashboard component when the user is logged in
function MyTeamDashboard({ team, upcomingMatches, pastMatches }: { team: Team; upcomingMatches: Match[]; pastMatches: Match[] }) {
  const totalFantasyPoints = team.players.reduce(
    (sum, player) => sum + (player.fantasyPointsEarned ?? 0),
    0
  );
  const nextMatch = upcomingMatches[0];

  return (
    <div className="space-y-8">
      <MyTeamHeader team={team} />
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
            <SchedulingCard upcomingMatches={upcomingMatches} team={team} />
            <NextMatchCard match={nextMatch} teamId={team.id} />
          </div>
          <TeamStatsGrid team={team} />
          <PlayerAnalyticsTable players={team.players} />
        </div>
        <div className="lg:col-span-1 space-y-6">
          <TeamStatusCard team={team} />
          <RosterCard team={team} upcomingMatches={upcomingMatches} />
           <Card className="shadow-lg">
                <CardHeader>
                    <CardTitle className="flex items-center text-primary">
                        <Crown className="mr-2" />
                        Fantasy Performance
                    </CardTitle>
                </CardHeader>
                <CardContent className="text-center">
                    <p className="text-4xl font-bold text-foreground">{totalFantasyPoints.toFixed(1)}</p>
                    <p className="text-muted-foreground">Total fantasy points generated by your players.</p>
                </CardContent>
            </Card>
        </div>
      </div>
      <MatchHistoryTable matches={pastMatches} teamId={team.id} />
    </div>
  );
}

// The prompt to show when the user is not logged in
function LoginPrompt() {
    const { signInWithDiscord } = useAuth();
    return (
      <Card className="shadow-xl max-w-2xl mx-auto">
        <CardHeader className="text-center">
          <ShieldQuestion className="h-16 w-16 mx-auto text-primary mb-4" />
          <CardTitle className="text-4xl font-bold text-primary">Team Dashboard</CardTitle>
          <CardDescription className="text-lg text-muted-foreground">
            Log in with Discord to manage your team or register a new one.
          </CardDescription>
        </CardHeader>
        <CardContent className="text-center space-y-4">
          <Button onClick={signInWithDiscord} size="lg" className="w-full bg-[#5865F2] text-white hover:bg-[#4752C4] hover:text-white">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" className="mr-2"><path d="M19.54 0c1.356 0 2.46 1.104 2.46 2.472v21.528l-2.58-2.28-1.452-1.344-1.536-1.428.636 2.22h-13.62c-1.356 0-2.46-1.104-2.46-2.472v-16.224c0-1.368 1.104-2.472 2.46-2.472h16.08zm-4.632 15.672c2.652-.084 3.672-1.824 3.672-1.824 0-3.864-1.728-6.996-1.728-6.996-1.728-1.296-3.372-1.26-3.372-1.26l-.168.192c2.04.624 2.988 1.524 2.988 1.524-2.256-.816-4.008-1.524-5.964-1.524-1.956 0-3.708.708-5.964 1.524 0 0 .948-.9 2.988-1.524l-.168-.192c0 0-1.644-.036-3.372 1.26 0 0-1.728 3.132-1.728 6.996 0 0 1.02 1.74 3.672 1.824 0 0 .864-.276 1.68-.924-1.608.972-3.12 1.956-3.12 1.956l1.224 1.056s1.38-.348 2.808-.936c.912.42 1.872.576 2.784.576.912 0 1.872-.156 2.784-.576 1.428.588 2.808.936 2.808.936l1.224-1.056s-1.512-.984-3.12-1.956c.816.648 1.68.924 1.68.924zm-6.552-5.616c-.684 0-1.224.6-1.224 1.332 0 .732.552 1.332 1.224 1.332.684 0 1.224-.6 1.224-1.332.012-.732-.54-1.332-1.224-1.332zm4.38 0c-.684 0-1.224.6-1.224 1.332 0 .732.552 1.332 1.224 1.332.684 0 1.224-.6 1.224-1.332s-.54-1.332-1.224-1.332z"/></svg>
            Login with Discord
          </Button>
        </CardContent>
      </Card>
    );
}

// Prompt for logged-in users without a team
function NoTeamPrompt() {
    const { user } = useAuth();
    const { toast } = useToast();

    const handleCopyId = () => {
        if (user?.uid) {
            navigator.clipboard.writeText(user.uid);
            toast({
                title: "User ID Copied!",
                description: "Your Firebase User ID has been copied to the clipboard.",
            });
        }
    };

    return (
        <Card className="shadow-xl max-w-2xl mx-auto">
            <CardHeader className="text-center">
                <UserPlus className="h-16 w-16 mx-auto text-primary mb-4" />
                <CardTitle className="text-4xl font-bold text-primary">Welcome!</CardTitle>
                <CardDescription className="text-lg text-muted-foreground">
                    It looks like you don't have a team yet.
                </CardDescription>
            </CardHeader>
            <CardContent className="text-center space-y-6">
                <p className="text-muted-foreground">
                    Ready to compete? Register your team now to join the tournament!
                </p>
                <Button asChild size="lg">
                    <Link href="/register">
                        Register a New Team
                    </Link>
                </Button>
                 {user?.uid && (
                    <Card className="mt-6 bg-muted/50 p-4 text-left">
                        <h3 className="text-sm font-semibold text-foreground flex items-center mb-2">
                           <Fingerprint className="h-4 w-4 mr-2 text-accent"/> For Admin Setup
                        </h3>
                        <p className="text-xs text-muted-foreground mb-3">To become an admin, copy your User ID below and add it to the 'admins' collection in your Firestore database.</p>
                        <div className="flex items-center space-x-2">
                            <input
                                readOnly
                                value={user.uid}
                                className="flex-1 p-2 bg-background border rounded-md text-xs font-mono"
                            />
                            <Button variant="ghost" size="icon" onClick={handleCopyId} aria-label="Copy User ID">
                                <Copy className="h-4 w-4"/>
                            </Button>
                        </div>
                    </Card>
                )}
            </CardContent>
        </Card>
    );
}

// The main page component that handles logic
export default function MyTeamPage() {
  const { user } = useAuth();
  const [teamId, setTeamId] = React.useState<string | null>(null);
  const [teamData, setTeamData] = React.useState<{ team: Team | undefined; upcomingMatches: Match[]; pastMatches: Match[] } | null>(null);
  const [isLoading, setIsLoading] = React.useState(true);
  
  React.useEffect(() => {
    async function checkUserTeam() {
      if (user) {
        setIsLoading(true);
        const id = await getUserTeam(user.uid);
        setTeamId(id);
        if (id) {
          const data = await getMyTeamData(id);
          setTeamData(data);
        }
        setIsLoading(false);
      } else {
        setIsLoading(false);
      }
    }
    checkUserTeam();
  }, [user]);
  
  if (isLoading) {
    return (
      <div className="flex justify-center items-center h-64">
        <Loader2 className="h-16 w-16 animate-spin text-primary" />
      </div>
    );
  }

  if (!user) {
    return <LoginPrompt />;
  }

  if (teamId && teamData?.team) {
    return (
      <MyTeamDashboard 
        team={teamData.team} 
        upcomingMatches={teamData.upcomingMatches} 
        pastMatches={teamData.pastMatches} 
      />
    );
  }
  
  return <NoTeamPrompt />;
}
